const ACTION_DISPLAY_NAMES: Record<string, string> = {
  bprel: "Release",
  bpre: "End",
  bpr: "Press",
  bstn: "ButtonStep ElseIf",
  bste: "End",
  bst0: "Button Off",
  cb: "Code Block",
  c: "Comment Block",
  el: "Else",
  ei: "Else if",
  en: "End",
  if: "If",
  sn: "Element Name",
  elrel: "Rotate Right",
  elre: "End",
  elr: "Rotate Left",
  eprlrel: "Just Rotate Right",
  eprlrei1: "Push and Rotate Right",
  eprlrei2: "Just Rotate Left",
  eprlre: "End",
  eprlr: "Push and Rotate Left",
  eprel: "Just Rotate",
  epre: "End",
  epr: "Push and Rotate",
  for: "Repeater Loop",
  fen: "End",
  fst: "Function",
  ggms: "GamePad Axis",
  ggbs: "GamePad Button",
  glat: "Start Animation",
  glap: "Stop Animation",
  glc: "Color",
  glp: "Intensity",
  glut: "Lookup",
  enl: "End",
  gks: "Keyboard",
  gms: "MIDI",
  gmsh: "MIDI 14",
  gmnp: "MIDI NRPN",
  gmss: "SysEX",
  gmbs: "Mouse Button",
  gmms: "Mouse Move",
  raw: "RAW code",
  rse: "Reset Encoder",
  sbc: "Button Mode",
  sec: "Encoder Mode",
  sen: "Endless Mode",
  spc: "Potmeter Mode",
  sglc: "Simple Color",
  gts: "Clock Source",
  gtt: "Start",
  gtp: "Stop",
  g: "Global",
  l: "Locals",
  s: "Self",
};

export function getActionDisplayName(short: string): string | null {
  if (!short) return null;
  return ACTION_DISPLAY_NAMES[short] ?? null;
}
